spring:
  resources:
    add-mappings: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**
  application:
    name: global
  cloud:
    config:
      profile: dev  # 指定配置文件的环境
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/sumingsoftware/spring-cloud      # git仓库地址
          search-paths: /                                     # 配置文件所在的目录
          username: sumingabc@126.com                        # git用户名和密码
          password:          # 由于公共仓库可以不用用户名和密码，可以不用设置
          label: master                 # 分支
server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/